# Generated by Django 4.2.11 on 2024-03-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembrePersonnel',
            fields=[
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('grade', models.CharField(choices=[('slt', 'SLT'), ('lt', 'LT')], max_length=3, verbose_name='Grade')),
                ('service', models.CharField(choices=[('mecanique', 'Mécanique'), ('electrique', 'Électrique')], max_length=10, verbose_name='Service')),
                ('numero', models.IntegerField(verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Photo')),
                ('statut', models.CharField(choices=[('mecanique', 'Mécanique'), ('electrique', 'Électrique')], default='Présent', max_length=10, verbose_name='Statut')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Present', 'Présent'), ('Absent', 'Absent')], default='Present', max_length=10)),
                ('motif', models.CharField(choices=[('ASM', 'ASM'), ('Permission', 'Permission')], max_length=255)),
                ('date_depart', models.DateField(null=True)),
                ('heure_depart', models.TimeField(null=True)),
                ('date_arrivee', models.DateField(null=True)),
                ('heure_arrivee', models.TimeField(null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='interfaces.membrepersonnel')),
            ],
        ),
    ]
