# Generated by Django 4.2.11 on 2024-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_remove_membrepersonnel_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='statut',
        ),
        migrations.AddField(
            model_name='membrepersonnel',
            name='statut',
            field=models.CharField(choices=[('mecanique', 'Mécanique'), ('electrique', 'Électrique')], default='Present', max_length=10),
        ),
    ]
