# Generated by Django 4.2.11 on 2024-03-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0003_remove_absence_statut_membrepersonnel_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrepersonnel',
            name='statut',
            field=models.CharField(choices=[('Présent', 'Présent'), ('Absent', 'Absent')], default='Present', max_length=10),
        ),
    ]
