# Generated by Django 4.2.11 on 2024-04-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0005_alter_absence_date_arrivee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrepersonnel',
            name='statut',
        ),
        migrations.AlterField(
            model_name='membrepersonnel',
            name='grade',
            field=models.CharField(choices=[('Soldat deuxieme classe', 'Soldat deuxième classe'), ('Soldat première classe', 'Soldat prémière classe'), ('Caporal', 'Caporal'), ('Caporal chef', 'Caporal chef'), ('Sergent', 'Sergent'), ('Sergent chef', 'Sergent Chef'), ('Adjudant', 'Adjudant'), ('Adjudant chef', 'Adjudant chef'), ('Aspirant', 'Aspirant'), ('Sous lieutenant', 'Sous lieutenant'), ('Lieutenant', 'Lieutenant'), ('Capitaine', 'Capitaine'), ('Commandant', 'Commandant'), ('Lieutenant colonel', 'Lieutenant colonel'), ('Colonel', 'Colonel'), ('Colonel major', 'Colonel major'), ('Géneral de brigade aerienne', 'Géneral de brigade aerienne'), ('Géneral de division', 'Géneral de division'), ("Géneral de corps d'armée", "Géneral de corps d'armée"), ("Géneral d'armée", "Géneral d'armée")], max_length=30, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='membrepersonnel',
            name='service',
            field=models.CharField(choices=[('SGMA1', 'SGMA1'), ('SGMA2', 'SGMA2'), ('SGMA3', 'SGMA3'), ('SGAS', 'SGAS'), ('SGMMR', 'SGMMR'), ('SGRT', 'SGRT'), ('BCT', 'BCT'), ('BST', 'BST'), ('BPI', 'BPI'), ('BTD', 'BTD'), ('Secretariat', 'Secretariat'), ('Comptabilité', 'Comptabilité'), ('Fourier', 'Fourier')], max_length=20, verbose_name='Service'),
        ),
    ]
