# Generated by Django 4.2.11 on 2024-04-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0006_remove_membrepersonnel_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrepersonnel',
            name='satut',
            field=models.CharField(choices=[('Présent', 'Présent'), ('Absent', 'Absent')], default='Présent', max_length=30, verbose_name='Statut'),
        ),
    ]
