# Generated by Django 4.2.11 on 2024-04-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0007_membrepersonnel_satut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membrepersonnel',
            old_name='satut',
            new_name='statut',
        ),
    ]
