# Generated by Django 4.2.11 on 2024-04-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0008_rename_satut_membrepersonnel_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='duree_absence',
            field=models.FloatField(default=0),
        ),
    ]
