# Generated by Django 4.2.11 on 2024-04-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0009_absence_duree_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='lieu',
            field=models.CharField(blank=True, default='Lieu inconnu', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='motif_asm',
            field=models.CharField(blank=True, choices=[('ASM', 'ASM')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='motif_pcd',
            field=models.CharField(blank=True, choices=[('Recuperation_de_travail', 'Récupération de travail'), ('Recuperation_de_garde', 'Récupération de garde'), ('Affaires_administratives', 'Affaires administratives'), ('Récupération_apres_mission', 'Récupération après retour de mission'), ('Problèmes_sociaux', 'Problèmes sociaux'), ('Récupération_de_permanence', 'Récupération de permanence'), ('Préparation_à_la_garde', 'Préparation à la garde')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='motif_pld',
            field=models.CharField(blank=True, choices=[('Droit_annuel', 'Droit annuel')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='motif_repos_medical',
            field=models.CharField(blank=True, choices=[('Repos_medical', 'Repos médical'), ('Consultation_médicale', 'Consultation médicale')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='motif_service_interieur',
            field=models.CharField(blank=True, choices=[('Garde', 'Garde'), ('Mission', 'Mission'), ('Détaché', 'Détaché')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='nature',
            field=models.CharField(blank=True, default='Nature inconnue', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('ASM', 'ASM'), ('PLD', 'PLD'), ('PCD', 'PCD'), ('Repos_medical', 'Repos médical'), ('Service_interieur', 'Service intérieur')], default='ASM', max_length=250),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif',
            field=models.CharField(default='Autre motif', max_length=255),
        ),
        migrations.AlterField(
            model_name='absence',
            name='personnel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interfaces.membrepersonnel'),
        ),
    ]
