# Generated by Django 4.2.11 on 2024-04-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0010_absence_lieu_absence_motif_asm_absence_motif_pcd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif_service_interieur',
            field=models.CharField(blank=True, choices=[('Garde', 'Garde'), ('Mission', 'Mission'), ('Détaché', 'Détaché'), ('Cours', 'Cours')], default=None, max_length=50, null=True),
        ),
    ]
