# Generated by Django 4.2.11 on 2024-04-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0011_alter_absence_motif_service_interieur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='motif',
        ),
    ]
