# Generated by Django 4.2.11 on 2024-04-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0012_remove_absence_motif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='nature',
        ),
    ]
