# Generated by Django 4.2.11 on 2024-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0013_remove_absence_lieu_remove_absence_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif_pcd',
            field=models.CharField(blank=True, choices=[('Récupération de travail', 'Récupération de travail'), ('Récupération de garde', 'Récupération de garde'), ('Affaires administratives', 'Affaires administratives'), ('Récupération après retour de mission', 'Récupération après retour de mission'), ('Problèmes sociaux', 'Problèmes sociaux'), ('Récupération de permanence', 'Récupération de permanence'), ('Préparation à la garde', 'Préparation à la garde')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif_repos_medical',
            field=models.CharField(blank=True, choices=[('Repos médical', 'Repos médical'), ('Consultation médicale', 'Consultation médicale')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('ASM', 'ASM'), ('PLD', 'PLD'), ('PCD', 'PCD'), ('Repos médical', 'Repos médical'), ('Service intérieur', 'Service intérieur')], default='ASM', max_length=250),
        ),
    ]
