# Generated by Django 4.2.11 on 2024-04-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0015_alter_absence_type_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif_pcd',
            field=models.CharField(blank=True, choices=[('Recuperation_de_travail', 'Récupération de travail'), ('Recuperation_de_garde', 'Récupération de garde'), ('Affaires_administratives', 'Affaires administratives'), ('Recuperation_apres_mission', 'Récupération après retour de mission'), ('Problemes_sociaux', 'Problèmes sociaux'), ('Recuperation_de_permanence', 'Récupération de permanence'), ('Preparation_a_la_garde', 'Préparation à la garde')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif_repos_medical',
            field=models.CharField(blank=True, choices=[('Repos_medical', 'Repos médical'), ('Consultation_medicale', 'Consultation médicale')], default=None, max_length=50, null=True),
        ),
    ]
