# Generated by Django 4.2.11 on 2024-04-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0016_alter_absence_motif_pcd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif_asm',
            field=models.CharField(blank=True, choices=[('ASM', 'ASM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif_pcd',
            field=models.CharField(blank=True, choices=[('Recuperation_de_travail', 'Récupération de travail'), ('Recuperation_de_garde', 'Récupération de garde'), ('Affaires_administratives', 'Affaires administratives'), ('Recuperation_apres_mission', 'Récupération après retour de mission'), ('Problemes_sociaux', 'Problèmes sociaux'), ('Recuperation_de_permanence', 'Récupération de permanence'), ('Preparation_a_la_garde', 'Préparation à la garde')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif_pld',
            field=models.CharField(blank=True, choices=[('Droit_annuel', 'Droit annuel')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif_repos_medical',
            field=models.CharField(blank=True, choices=[('Repos_medical', 'Repos médical'), ('Consultation_medicale', 'Consultation médicale')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif_service_interieur',
            field=models.CharField(blank=True, choices=[('Garde', 'Garde'), ('Mission', 'Mission'), ('Detache', 'Détaché'), ('Cours', 'Cours')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfaces.membrepersonnel'),
        ),
    ]
