# Generated by Django 4.2.11 on 2024-04-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0017_alter_absence_motif_asm_alter_absence_motif_pcd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif_repos_medical',
            field=models.CharField(blank=True, choices=[('Repos_medical', 'Repos médical'), ('PTC', 'PTC'), ('Consultation_medicale', 'Consultation médicale')], max_length=50, null=True),
        ),
    ]
