# Generated by Django 4.2.11 on 2024-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0018_alter_absence_motif_repos_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif_repos_medical',
            field=models.CharField(blank=True, choices=[('Repos_medical', 'Repos médical'), ('PTC', 'PTC'), ('Consultation_medicale', 'Consultation médicale')], default='Repos médical', max_length=50, null=True),
        ),
    ]
