# Generated by Django 4.2.11 on 2024-04-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0019_alter_absence_motif_repos_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif_asm',
            field=models.CharField(blank=True, choices=[('ASM', 'ASM'), ('Retard', 'Retard')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif_repos_medical',
            field=models.CharField(blank=True, choices=[('Repos_médical', 'Repos_médical'), ('PTC', 'PTC'), ('Consultation_médicale', 'Consultation_médicale')], default='Repos_médical', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('ASM', 'ASM'), ('PLD', 'PLD'), ('PCD', 'PCD'), ('Repos_médical', 'Repos_médical'), ('Service_intérieur', 'Service_intérieur')], default='ASM', max_length=250),
        ),
    ]
