# Generated by Django 4.2.11 on 2024-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0020_alter_absence_motif_asm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('ASM', 'ASM'), ('PLD', 'PLD'), ('PCD', 'PCD'), ('Repos_médical', 'Repos médical'), ('Service_intérieur', 'Service intérieur')], default='ASM', max_length=250),
        ),
    ]
