# Generated by Django 4.2.11 on 2024-04-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0021_alter_absence_type_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='motif_repos_medical',
            field=models.CharField(blank=True, choices=[('Repos_médical', 'Repos médical'), ('PTC', 'PTC'), ('Consultation_médicale', 'Consultation médicale')], default='Repos_médical', max_length=50, null=True),
        ),
    ]
