# Generated by Django 4.2.11 on 2024-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0022_alter_absence_motif_repos_medical'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('Actuelle', 'Actuelle'), ('Passée', 'Passée')], default='Passée', max_length=30, verbose_name='Statut'),
        ),
    ]
